### ISSUE TITLE
[Lesson 0] 시작해볼까요? 

### ISSUE THREAD

**Issue by Choiyos** [homenet12/codeLesson#1]
레슨을 시작해볼까요 :)

화면에 문자를 표현할 수 있는 개발 환경을 기반으로 프로젝트를 시작하여. 'hello world'를 화면 상에 출력하는 코드를 구현 후. push해주세요.

- 제한조건
  - 개발 환경은 GUI Tool이나 Console창 등을 기본으로 하며, 나머지 환경은 자유롭게 정한다.
-  개발 환경 예시
  - React + Typescript
  - React + Javascript
  - Vue.js + Javascript
  - Java + Eclips
  - Java + Swing
  - C# + Winform
  - C# + WPF
  - C Console
  - Java Console
  - Html + Javascript
  - etc...

커밋시에는 커밋 타이틀 가장 앞에 # + 커밋과 관련된 이슈 넘버(현재는 1)을 붙여 커밋합니다.
ex) [#1] 초기 세팅

**Comment by Choiyos** [comment]
또한 Repository Settings에서 제 계정을 Maintain 이상으로 설정하여 초대해주세요.
![image](https://user-images.githubusercontent.com/31244245/121463218-97223b80-c9ec-11eb-8d89-920c1f035ac1.png)

**Comment by homenet12** [comment]
계정을 알려주세요

**Comment by Choiyos** [comment]
> 계정을 알려주세요

제 아이디 Choiyos를 치면 아마 나올것 같네용

**Comment by homenet12** [comment]
올렸어욜!!

**Comment by Choiyos** [comment]
커밋시 Summary(커밋 제목) 부분에 [#issueNumber]를 접두어로 붙여주세요!
그래야 현재 이슈 관련된 커밋이 어떤게 진행되었는지 볼 수 있습니당
#1

**Comment by Choiyos** [comment]
추가 제한 조건 : 웹에서 볼 수 있는 배포환경을 구축해야 한다. (aka. CI/CD), (ex. netlify)

**Comment by homenet12** [comment]
외부망에서도 볼 수 있어야 한다는건가요

**Comment by Choiyos** [comment]
> 외부망에서도 볼 수 있어야 한다는건가요

맞습니다~
무료로 배포하는 환경을 제공하는 서비스가 많으니 찾아보셔도 좋습니당

**Comment by homenet12** [comment]
https://homenet12.github.io/codeLesson/TEST1.html
이렇게 하면 됩니깡

**Comment by Choiyos** [comment]
> https://homenet12.github.io/codeLesson/TEST1.html
> 이렇게 하면 됩니깡

좋습니다 !
