### ISSUE TITLE
[Lesson 1] 첫 Pattern 

### ISSUE THREAD

**Issue by Choiyos** [homenet12/codeLesson#2]
# [Lesson 1] 첫 Pattern

아래와 같이 모양이 화면상에 표시되도록 만들어주세요.
 
```
* 
**
***
****
***** 
```

- 제한조건
  - hello world를 구현한 프로젝트 코드를 수정해서 만든다.
  - view는 자유롭게 구성한다.

**Comment by homenet12** [comment]
https://homenet12.github.io/codeLesson/TEST2.html
#2 렛츠 투

**Comment by Choiyos** [comment]
간단하게 종료~
