### ISSUE TITLE
[Lesson 2] 사용자가 입력가능하도록 만든다.

### ISSUE THREAD

**Issue by Choiyos** [homenet12/codeLesson#3]
# [Lesson 2] 사용자가 입력가능하도록 만든다.

Lesson 1의 프로젝트를 수정하여 사용자가 몇 줄을 찍을 것인지 입력할 수 있도록 한다.

``` 
How many lines? (1..100)  7
*
**
***
****
*****
******
******* 
```

- 제한조건
  - 사용자는 1 부터 100 까지의 값을 입력할 수 있다. 
  - 사용자가 0 이나 마이너스 값을 치는 경우에는 경고를 표시하고 input 을 다시 요구한다. 100 보다 큰 경우에도 마찬가지이다.
  - 사용자가 정상 값을 칠 때까지 계속 입력을 받는다.

**Comment by homenet12** [comment]
입력해버리기~~https://homenet12.github.io/codeLesson/TEST3.html

**Comment by Choiyos** [comment]
@homenet12 이슈번호를 붙인 다음 구현 내용을 적어주시면 좋습니다.
예시) `[#3] 사용자가 입력 가능하도록 수정`

**Comment by Choiyos** [comment]
제한조건에 대해 확인 후 반영 부탁드립니다!
@homenet12

**Comment by Choiyos** [comment]
참고로 구현내용에 대해 적을 때에는 Summary부분에 간략한 정보,
추가적인 정보를 기재할 때에는 Description부분에 적어주시면 좋습니다.
이슈번호를 붙이는 첫 줄까진 Summary, 그 이후 한 두번의 줄바꿈 하고 나서 Description을 적어주시면 됩니다.
- 예시
```
[#3] 사용자 입력에 텍스트 입력시 경고

- input을 이용하여 경고
- 경고 창 닫으면 다시 input으로 포커싱 되도록 추가
```

**Comment by homenet12** [comment]
수정완료~

**Comment by Choiyos** [comment]
입력 숫자가 100넘는 경우에도 출력이 진행됩니다. 수정 부탁드릴게요!

**Comment by Choiyos** [comment]
> 입력 숫자가 100넘는 경우에도 출력이 진행됩니다. 수정 부탁드릴게요!

아직 링크에 반영이 안된 것인가...

**Comment by homenet12** [comment]
엥 100이상 걸리는디요

**Comment by homenet12** [comment]
캐시날리고 다시 부탁염~~~

**Comment by Choiyos** [comment]
> 캐시날리고 다시 부탁염~~~

확인했습니다.
- 추가 요청사항
- [ ] 숫자가 아닌 텍스트 등의 문자 입력시에도 경고창 띄우기
- [ ] input에 숫자 입력 후 엔터를 쳤을 때에도 `등록`을 누를 때와 마찬가지의 효과 추가
- [ ] `등록`이라는 버튼의 네이밍이 어떤것을 등록한다는 것인지 애매한데, 새로운 이름 제안

**Comment by Choiyos** [comment]
한글 혹은 영어가 입력되었을 때에는 아무 반응이 없는데, 확인 부탁드려요.
브라우저 환경은 윈도우의 크롬과 파이어폭스 모두 동일합니다.

**Comment by Choiyos** [comment]
> 한글 혹은 영어가 입력되었을 때에는 아무 반응이 없는데, 확인 부탁드려요.
> 브라우저 환경은 윈도우의 크롬과 파이어폭스 모두 동일합니다.

확인 완료

**Comment by homenet12** [comment]
내용 확인했고 수정했습니다.
캐시 삭제 후 테스트 요청 드립니다

**Comment by Choiyos** [comment]
![image](https://user-images.githubusercontent.com/31244245/121488204-d2813200-ca0d-11eb-99a8-d0ec4a19ae01.png)
소수점에 대한 처리 부탁드립니다

- 선택사항
  - 소수점을 입력할 수 없도록 한다
  - 소수점이 입력되면 반올림, 올림, 내림 중 한가지를 선택하여 표시한다.
    - 이 경우 어느 방식으로 선택했는지 사용자에게 알려준다

**Comment by homenet12** [comment]
소수점 입력할 수 없게 수정되었습니다

**Comment by Choiyos** [comment]
더이상 입력 이슈가 없으므로 close.

**Comment by Choiyos** [comment]
추가 이슈 발견으로 reopen.
![image](https://user-images.githubusercontent.com/31244245/121492239-abc4fa80-ca11-11eb-9859-f1c75acae1a9.png)

**Comment by homenet12** [comment]
추가 이슈 수정 완료
