### ISSUE TITLE
# [Lesson 3] 새로운 Pattern

### ISSUE THREAD

**Issue by Choiyos** [homenet12/codeLesson#4]
# [Lesson 3] 새로운 Pattern

아래의 2 가지 Pattern 을 추가하고 (총 3 개의 Pattern 이 된다)
사용자가 원하는 Pattern 을 선택할 수 있도록 한다. 
화면 구성은 스스로 제안한다.

```
- Pattern 추가
*****
 ****
  ***
   **
    * 
 
- Pattern 추가
   *
  ***
 *****
  ***
   * 
```

- 제한사항
  - 사용자가 이해하기 쉬운 화면을 제안한다.
  - 다이아몬드 형태의 입력은 홀수만 입력되도록 한다.

**Comment by homenet12** [comment]
고고씽 https://homenet12.github.io/codeLesson/TEST4.html

**Comment by Choiyos** [comment]
다이아몬드 패턴에서 숫자가 아닌 값을 입력했을 때, 혹은 범위 밖의 값을 입력했을 때
안내문구가 나온 다음 무조건 홀수를 입력해달라는 창이 한번 더 뜨는데, 중복으로 알릴 필요 없이 한 번만 알려줄 수 있도록 수정 되면 좋을 것 같습니다.

**Comment by homenet12** [comment]
렛츠 두디스

**Comment by Choiyos** [comment]
선택한 패턴 예시와 출력된 패턴의 모양이 다르네요.
선택된 패턴에 대한 표기 방법을 고려하여 제안 주세용, 아님 단순 변경해도 됩니다
![image](https://user-images.githubusercontent.com/31244245/121978637-93fbc680-cdc3-11eb-8f62-f71ae2672a73.png)

**Comment by Choiyos** [comment]
![image](https://user-images.githubusercontent.com/31244245/121978701-bd1c5700-cdc3-11eb-82dc-ab6ec0e4018b.png)
페이지가 새로고침 되었을 때 기본적으로 라디오버튼이 선택되면 편할 것 같네요.
선택되지 않은 상태로 출력을 눌렀을 때 라디오버튼 선택하라는 경고가 큰 의미가 있어보이진 않아서요.

**Comment by homenet12** [comment]
> 선택된 패턴 예시와 출력 된 패턴의 모양이 다르 네요.
> 선택한 패턴에 대한 표기 방법을 고려하여 제안 주세용, 아님 단순 변경해도됩니다
> ![영상](https://user-images.githubusercontent.com/31244245/121978637-93fbc680-cdc3-11eb-8f62-f71ae2672a73.png)

브라우저 어떤거 사용중이신지 확인 부탁드립니다

**Comment by Choiyos** [comment]
크롬 사용중입니다~ @homenet12

**Comment by Choiyos** [comment]
이슈는 왜 닫으셨나요 ?_?

**Comment by homenet12** [comment]
이슈를 닫는게 뭔가요? ㅋㅋㅋ

**Comment by homenet12** [comment]
뭐 잘못눌렀나보네

**Comment by Choiyos** [comment]
아하 파이어폭스에서는 별이 왼쪽정렬되어 보이는군요
![image](https://user-images.githubusercontent.com/31244245/121981708-1fc42180-cdc9-11eb-924f-4385d88f4fab.png)

**Comment by Choiyos** [comment]
이참에 cross-browsing 지원도 ... ^^

**Comment by homenet12** [comment]
수정했습니다ㅇ아아아

**Comment by homenet12** [comment]
오류 발견으로 재수정하겠습니다아아아

**Comment by homenet12** [comment]
수정완료~~

**Comment by Choiyos** [comment]
패턴을 변경할 때, 라디오버튼을 정확히 눌러야해서 불편함이 느껴지는데, 패턴 글자를 클릭해도 변경이 가능하도록 수정 부탁드려요~

**Comment by homenet12** [comment]
수정 완료

**Comment by Choiyos** [comment]
완료!
