### ISSUE TITLE
# [Lesson 4] 이전 패턴 기록 및 Pattern 추가 

### ISSUE THREAD

**Issue by Choiyos** [homenet12/codeLesson#5]
# [Lesson 4] 이전 패턴 기록 및 Pattern 추가 

1. 한번 출력된 이전 패턴 1개가 기록되어 보여야 한다.
    - 이전에 출력된 패턴을 보기 위함이다.
2. 아울러, 아래의 Pattern 을 추가한다. 

```
- Pattern 추가
   ***
  ***
 *** 
 
- Pattern 추가
   ***
  **
 * 
```

- 제한사항
  - 사용자가 이해하기 쉬운 화면을 제안한다.

**Comment by homenet12** [comment]
위에 꺼가 숫자 몇 입력한 상태입니까

**Comment by Choiyos** [comment]
3입니다~ @homenet12

**Comment by homenet12** [comment]
두번째 패턴 짝수만 되는건가요?

**Comment by Choiyos** [comment]
아닙니다~

**Comment by homenet12** [comment]
가봅시다~

**Comment by Choiyos** [comment]
![image](https://user-images.githubusercontent.com/31244245/122018389-c5918380-cdfd-11eb-87b7-29d5f36fe157.png)
숫자가 입력이 되면 가로도 길어져야합니다!

**Comment by Choiyos** [comment]
이전에 출력되었던 패턴을 아래에 표시하는 게 아니라 아예 리스트로 한개씩 뒤로갈 수 있도록 만드셨군요... 흥미돋네요

**Comment by homenet12** [comment]
세로도 길어져야 한다는거죠?

**Comment by homenet12** [comment]
스택을 구현한거쥬

**Comment by homenet12** [comment]
아니 스택을 쓴거지..

**Comment by homenet12** [comment]
수정완료

**Comment by Choiyos** [comment]
아 넴

> 세로도 길어져야 한다는거죠?

가로가 추가되어야 한다는 걸 잘못말했네엽

**Comment by Choiyos** [comment]
좋네요. 특이사항 없으므로 완료~
